version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: finance-ai-database
    environment:
      POSTGRES_USER: finance
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: finance-ai
    ports:
      - "5433:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: finance-ai-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://finance:12345@host.docker.internal:5433/finance-ai?schema=public"

volumes:
  .postgres-data:
